package com.webservice.wsimport;

import java.net.MalformedURLException;

/**
 * This class was generated by executing following command in this package
 * wsimport -keep http://localhost:9999/ws/hello?wsdl
 */
public class HelloWorldClient {

	public static void main(String[] args) throws MalformedURLException {
		HelloWorldImplService helloService = new HelloWorldImplService();
		HelloWorld hello = helloService.getHelloWorldImplPort();
		
		System.out.println(hello.getHelloWorldAsString("Asia"));
	}

}
